
name: ansible-galaxy-action

on:
  workflow_dispatch:

jobs:
  test-galaxy-import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run ansible-galaxy-action in test mode
        uses: step-security/ansible-galaxy-action@release
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
